services:
  postgres:
    image: postgres:14.3-bullseye
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
